### ISSUE TITLE
[Suggestion] Turn this into Template Repo

### ISSUE THREAD

**Issue by OverlordZorn** [TACHarsis/hemtt-mod-template#1]
![grafik](https://github.com/TACHarsis/hemtt-mod-template/assets/56258612/25b74e24-8d4b-494f-9ae5-264a2821a3b9)

Seems like github has the feature to use a repo as a template, seems like this would be ideal for this repo here

**Comment by TACHarsis** [comment]
Will look into it.

**Comment by TACHarsis** [comment]
Ah, straight forward enough. Done.
